# Generated by Django 4.2.1 on 2023-05-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_ingeniero_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingeniero',
            name='user',
        ),
    ]
