# Generated by Django 4.2.1 on 2023-05-31 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_bitacora_ingeniero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='ingeniero',
            new_name='Ingeniero',
        ),
        migrations.AddField(
            model_name='ingeniero',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
