# Generated by Django 4.2.1 on 2023-05-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_ingeniero_bitacora_ingeniero_ingeniero_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingeniero',
            name='user',
        ),
    ]
