# Generated by Django 4.2.1 on 2023-05-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_ingeniero_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='Ingeniero',
            new_name='ingeniero',
        ),
    ]
