# Generated by Django 4.2.1 on 2023-06-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_ingeniero_bitacora_ingeniero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='ingeniero',
        ),
    ]
